Introduce sdc-usbkey set-variable, and use it.
Update the README a little.

diff --git a/bin/reflash b/bin/reflash
--- a/bin/reflash
+++ b/bin/reflash
@@ -711,23 +711,34 @@ sanity_check_usb()
             set -o xtrace
         fi
 
-        # Ensure we've got a platform + grub
-        if [[ ! -f /mnt/usbkey/boot/grub/menu.lst ]]; then
-            echo "Missing grub menu.lst, bailing" >&2
-            exit 1
-        fi
         if [[ -z \$(find /mnt/usbkey/os/ -name "boot_archive") ]]; then
             echo "Missing boot_archive, bailing" >&2
             exit 1
         fi
 
-        # Set default menu item to boot to 1 so we can boot unattended (we know
-        # this is a HN since we're reflashing, so don't boot the Compute Node
-        # image)
-        sed -e "s/^default.*$/default 1/" /mnt/usbkey/boot/grub/menu.lst \
-            > /mnt/usbkey/boot/grub/menu.lst.new \
-            && mv /mnt/usbkey/boot/grub/menu.lst.new \
-                /mnt/usbkey/boot/grub/menu.lst
+        #
+        # Make sure to boot from USB, so we can boot unattended (we know this is
+        # an HN since we're reflashing, so don't boot the CN image).
+        #
+        # sdc-usbkey might not be new enough for this; in that case, we know
+        # we're using grub.
+        #
+        if ! /opt/smartdc/bin/sdc-usbkey set-variable ipxe false 2>/dev/null; then
+
+            # Ensure we've got a platform + grub
+            if [[ ! -f /mnt/usbkey/boot/grub/menu.lst ]]; then
+                echo "Missing grub menu.lst, bailing" >&2
+                exit 1
+            fi
+
+            # Set default menu item to boot to 1 so we can boot unattended (we know
+            # this is a HN since we're reflashing, so don't boot the Compute Node
+            # image)
+            sed -e "s/^default.*$/default 1/" /mnt/usbkey/boot/grub/menu.lst \
+                > /mnt/usbkey/boot/grub/menu.lst.new \
+                && mv /mnt/usbkey/boot/grub/menu.lst.new \
+                    /mnt/usbkey/boot/grub/menu.lst
+        fi
 
         exit 0
 EOF
